from django.urls import path
from .views import (CampaignsActionCreateView, ClientLoginView, ClientDashboardView, ClientCouponView,
                    ClientScheduleBroadcastView,
                    ClientListView, ClientContactView, ClientCampaignsView, ClientCampaignCreationView,
                    ClientCampaignSettingView, ClientLogoutView, ClientSetPasswordView, ClientForgetPasswordView, DeleteTagView,
                    EditContactView, ClientAccountSettingView, ContactDeleteView, TagsWiseFilter, ClientUserView,
                    ClientUserEditView, ClientUserDeleteView, ContactListDeleteView, ContactListEditView,
                    ClientPhoneNumberView, ClientPhoneNumberGetView, ClientPhoneNumberDeleteView,
                    ClientPhoneNumberMakeDefultView,
                    ClientUserActiveUser, ClientUserStatusWiseFilter, ClientScheduleListBroadcastView,
                    ClientSentListBroadcastView,
                    CouponDeleteView, GetListNameUnique, ContactUserCouponView, ServerPasscodeCheckView,
                    CouponReedemView,
                    ContactUserUpdateView, ScheduleCron, SmartListCron, CouponExpireCron, CampaignsCreationView,
                    CampaignsEditView, CampaignsDeleteView, CampaignsActionEditView, CampaignsEditGetDataView,
                    CampaignsActionDeleteView,
                     ClientPhoneNoFilter, AddContactToListView,
                    CampaignStartView, SetPhoneNumberWebhook, ClientListBroadcastView, CampaignStartForDateBased,
                    ClientDashboardFilterView, GetListsForContactView,    
                     handle_incoming_message, AddCustomFieldsView,
                    EditCustomFieldView, DeleteCustomFieldView,ClientTagsView,EditTagView,DeleteTagView,ChatSystem,GetChatHistory, RemoveCampaign,
                    ClientReferralCampaignListView,ReferralCampaignDeleteView, GetContactReferralCampaignData, AddClaimVoucherContactUser, SendReferralCouponToContact
                    )

urlpatterns = [
   path('',ClientLoginView.as_view(),name="client-login"),
   path('client/client-logout/',ClientLogoutView.as_view(),name="client-logout"),
   path('client/client-dashboard/<str:id>/',ClientDashboardView.as_view(),name="client-dashboard"),
   path('client/client-coupon/<str:id>/',ClientCouponView.as_view(),name="client-coupon"),
   path('client/coupon-delete/<str:id>/',CouponDeleteView.as_view(),name="coupon-delete"),
   path('client/client-sch-broadcast/<str:id>/',ClientScheduleBroadcastView.as_view(),name="client-sch-broadcast"),
   path('client/client-list/<str:id>/',ClientListView.as_view(),name="client-list"),
   path('client/list-unique/<str:id>/',GetListNameUnique.as_view(),name="list-unique"),
   path('client/client-contact/<str:id>/',ClientContactView.as_view(),name="client-contact"),
   path('client/client-campaigns/<str:id>/',ClientCampaignsView.as_view(),name="client-campaigns"),
   path('client/client-settings/<str:id>/',ClientCampaignSettingView.as_view(),name="client-settings"),
   path('client/client-campaign-create/<str:id>/',ClientCampaignCreationView.as_view(),name="client-campaign-create"),
   path('client/client-forget-password/',ClientForgetPasswordView.as_view(),name="client-forget-password"),
   path('client/client-reset-password/<str:uuid>/',ClientSetPasswordView.as_view(),name="client_reset_password"),
   path('client/contact-edit/',EditContactView.as_view(),name="contact-edit"),
   path('client/client/account-setting/',ClientAccountSettingView.as_view(),name="client-account-setting"),
   path('client/contact-delete/<str:id>/',ContactDeleteView.as_view(),name="contact-delete"),
   path('client/tag-wise-filter/',TagsWiseFilter.as_view(),name="tag_wise_filter"),
   path('client/client-user-setting/<str:id>/',ClientUserView.as_view(),name="client-user"),
   path('client/client-user-setting/<str:id>/',ClientUserView.as_view(),name="client-user"),
   path('client/client-user-edit/',ClientUserEditView.as_view(),name="client-user-edit"),
   path('client/client-user-delete/<str:id>/',ClientUserDeleteView.as_view(),name="client-user-delete"),
   path('client/client-list-delete/<str:id>/',ContactListDeleteView.as_view(),name="client-list-delete"),
   path('client/client-list-edit/',ContactListEditView.as_view(),name="client-list-edit"),
   path('client/client-phone-view/<str:id>/',ClientPhoneNumberView.as_view(),name="client-phone-view"),
   path('client/client-phone-get/<str:id>/',ClientPhoneNumberGetView.as_view(),name="client-phone-get"),
   path('client/client-phone-delete/<str:id>/',ClientPhoneNumberDeleteView.as_view(),name="client-phone-delete"),
   path('client/client-phone-make-defualt/<str:id>/',ClientPhoneNumberMakeDefultView.as_view(),name="client-phone-make-defualt"),
   path('client/client-user-status-filter/<str:id>/',ClientUserStatusWiseFilter.as_view(),name="client-user-status-filter"),
   path('client/client-user-active/',ClientUserActiveUser,name="client-user-active"),
   path('client/broadcast-schedule-listing/<str:id>/',ClientScheduleListBroadcastView.as_view(),name="broadcast-schedule-listing"),
   path('client/broadcast-sent-listing/<str:id>/',ClientSentListBroadcastView.as_view(),name="broadcast-sent-listing"),
   path('client/contact-coupon/<str:unique_id>/',ContactUserCouponView.as_view(),name="contact-coupon"),
   path('client/server-passcode/<str:unique_id>/',ServerPasscodeCheckView.as_view(),name="server-passcode"),
   path('client/coupon-reedem/<str:unique_id>/',CouponReedemView.as_view(),name="coupon-reedem"),
   path('client/contact-update/<str:unique_id>/',ContactUserUpdateView.as_view(),name="contact-update"),
   path('client/schedule/',ScheduleCron.as_view(),name="schedule"),
   path('client/smartlist/',SmartListCron.as_view(),name="smartlist"),
   path('client/couponvalidation/',CouponExpireCron.as_view(),name="couponvalidation"),
   path('client/campaign-creation/<str:id>/',CampaignsCreationView.as_view(),name="campaign-creation"),
   path('client/campaign-edit/<str:id>/',CampaignsEditView.as_view(),name="campaign-edit"),
   path('client/campaign-delete/<str:id>/',CampaignsDeleteView.as_view(),name="campaign-delete"),
   path('client/campaign-action-create/<str:id>/',CampaignsActionCreateView.as_view(),name="campaign-action-create"),
   path('client/campaign-action-edit/',CampaignsActionEditView.as_view(),name="campaign-action-edit"),
   path('client/campaign-edit-getdata/<str:id>/',CampaignsEditGetDataView.as_view(),name="campaign-edit-getdata"),
   path('client/campaign-action-delete/<str:id>/',CampaignsActionDeleteView.as_view(),name="campaign-action-delete"),
   path('client/campaign-start/',CampaignStartView.as_view(),name="campaign-start"),
   path('client/create-phone-webhook/',SetPhoneNumberWebhook.as_view(),name="create-phone-webhook"),
   path('client/phone_webhook/',handle_incoming_message,name="phone_webhook"),
   path('client/client-list-broadcast/<str:id>/',ClientListBroadcastView.as_view(),name="client-list-broadcast"),
   path('client/campaign-datebased/',CampaignStartForDateBased.as_view(),name="campaign-datebased"),
   path('client/client-dashboard-filter/',ClientDashboardFilterView.as_view(),name="client-dashboard-filter"),
   path('client/client-phone-no-filter/',ClientPhoneNoFilter.as_view(),name="client-phone-no-filter"),
   path('client/contact-list-table/',GetListsForContactView.as_view(),name="contact-list-table"),
   path('client/add-contact-to-list/',AddContactToListView.as_view(),name="add-contact-to-list"),
   path('client/add-custom-fields/<str:id>/',AddCustomFieldsView.as_view(),name="add-custom-fields"),
   path('client/client-custom-field/',EditCustomFieldView.as_view(),name="client-custom-field"),
   path('client/delete-custom-field/',DeleteCustomFieldView.as_view(),name="delete-custom-field"),
   path('client/client-tag-view/<str:id>/',ClientTagsView.as_view(),name="client-tag-view"),
   path('client/client-tag-edit/',EditTagView.as_view(),name="client-tag-edit"),
   path('client/client-tag-delete/<str:id>',DeleteTagView.as_view(),name="client-tag-delete"),
   path('client/chat-system/',ChatSystem.as_view(),name="chat-system"),
   path('client/get-chat-history/',GetChatHistory.as_view(),name="get-chat-history"),
   path('client/remove-complate-campaign/',RemoveCampaign.as_view(),name="remove-complate-campaign"),
   path('client/client-referral-campaign/<str:id>/',ClientReferralCampaignListView.as_view(),name="client-referral-campaign"),
   path('client/referral-campaign-delete/<str:id>/',ReferralCampaignDeleteView.as_view(),name="referral-campaign-delete"),
   path('client/get-contact-referral/<str:unique_id>/',GetContactReferralCampaignData.as_view(),name="get-contact-referral"),
   path('client/claim-voucher-cuntact/<str:unique_id>/',AddClaimVoucherContactUser.as_view(),name="claim-voucher-cuntact"),
   path('client/send-referral-coupon-contact/',SendReferralCouponToContact.as_view(),name="send-referral-coupon-contact"),


]