from .index_view import IndexView
from .agency import AgencyListView,AgencyUpdateView,AgencyDeleteView,AgencyCreateView,AgencyUserAjaxPagination
from .client import ClientListView,ClientUpdateView,ClientDeleteView,ClientCreateView,ClientAjaxPagination
