# Generated by Django 4.0.2 on 2022-02-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0006_alter_address_address'),
        ('aegency_user', '0002_rename_aegencyuser_agencyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('admin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('account_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.address')),
                ('aegency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_user', to='aegency_user.agencyuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('admin_user.admin',),
        ),
    ]
