# Generated by Django 4.0.1 on 2022-02-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_is_user_client_server_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
