# Generated by Django 4.0.1 on 2022-03-02 06:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0008_admin_is_forget_alter_admin_first_name_and_more'),
        ('client', '0003_alter_client_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('admin_user.activitytracking',),
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='client.Tags')),
                ('time_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.timezone')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
