# Generated by Django 4.0.1 on 2022-03-02 09:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_tags_contactuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
