# Generated by Django 4.0.1 on 2022-03-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_contactuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactuser',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
