# Generated by Django 4.0.1 on 2022-03-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0008_admin_is_forget_alter_admin_first_name_and_more'),
        ('client', '0006_contactuser_is_active_contactuser_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('name', models.CharField(max_length=30)),
                ('is_static', models.BooleanField(default=False)),
                ('is_smart', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(to='client.ContactUser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
