# Generated by Django 4.0.1 on 2022-03-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_contactlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='list_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
