# Generated by Django 4.0.1 on 2022-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphonenumber',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
