# Generated by Django 4.0.1 on 2022-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_clientphonenumber_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphonenumber',
            name='phone_sid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
