# Generated by Django 4.0.1 on 2022-03-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0008_admin_is_forget_alter_admin_first_name_and_more'),
        ('client', '0011_alter_clientphonenumber_phone_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCast',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_schdeule', models.BooleanField(default=False)),
                ('sch_date', models.DateTimeField(blank=True, null=True)),
                ('client_brodcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('contact_list', models.ManyToManyField(blank=True, null=True, to='client.ContactList')),
                ('contacts', models.ManyToManyField(blank=True, null=True, to='client.ContactUser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
