# Generated by Django 4.0.1 on 2022-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='contacts_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
