# Generated by Django 3.2.12 on 2022-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_broadcast_contacts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message_service_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
