# Generated by Django 3.2.12 on 2022-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_client_message_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_sent_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
