# Generated by Django 4.0.1 on 2022-03-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='client_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
