# Generated by Django 4.0.1 on 2022-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_coupon_client_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
