# Generated by Django 4.0.1 on 2022-03-29 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0019_coupon_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUserCoupon',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('is_read', models.BooleanField(default=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contactuser')),
                ('user_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.coupon')),
            ],
            options={
                'unique_together': {('user', 'user_coupon')},
            },
            bases=('admin_user.activitytracking',),
        ),
    ]
