# Generated by Django 4.0.1 on 2022-03-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_contactusercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_read_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
