# Generated by Django 4.0.1 on 2022-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_coupon_max_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusercoupon',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
