# Generated by Django 4.0.1 on 2022-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_contactusercoupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactusercoupon',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minmum_spend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='sales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
