# Generated by Django 4.0.1 on 2022-04-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_alter_contactuser_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='date_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='date_val',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='rev_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='rev_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='rev_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='rev_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
