# Generated by Django 4.0.1 on 2022-04-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0024_contactlist_date_from_contactlist_date_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('name', models.CharField(max_length=30)),
                ('is_defualt', models.BooleanField(default=False)),
            ],
            bases=('admin_user.activitytracking',),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('admin_user.activitytracking',),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_sending', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_double', models.BooleanField(default=False)),
                ('double_message', models.TextField(blank=True, null=True)),
                ('is_limit', models.BooleanField(default=False)),
                ('limit_message', models.TextField(blank=True, null=True)),
                ('in_progress_count', models.IntegerField(default=0)),
                ('complate_count', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('is_cancel', models.BooleanField(default=False)),
                ('on_reply', models.BooleanField(default=False)),
                ('is_cancel_tag', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(blank=True, max_length=30, null=True)),
                ('trigger_value', models.CharField(blank=True, max_length=30, null=True)),
                ('cancel_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_tag', to='client.tags')),
                ('double_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_keyword', to='client.keyword')),
                ('keyword_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_phone', to='client.clientphonenumber')),
                ('keyword_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_value', to='client.keyword')),
                ('send_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_phone', to='client.clientphonenumber')),
                ('sending_days', models.ManyToManyField(blank=True, null=True, to='client.Days')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
