# Generated by Django 4.0.1 on 2022-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_campaignaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='double_keyword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='keyword_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
