# Generated by Django 4.0.1 on 2022-04-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_alter_campaign_double_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='client_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
