# Generated by Django 4.0.1 on 2022-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_campaign_client_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='trigger_value',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='trigger_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
