# Generated by Django 4.0.1 on 2022-04-19 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_remove_campaign_trigger_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='on_cancel_keyword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='on_cancel_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
