# Generated by Django 4.0.1 on 2022-05-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0032_remove_campaign_cancel_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactToCampaign',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('is_true', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('campaign_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.campaignaction')),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contactuser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
