# Generated by Django 4.0.1 on 2022-05-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_contacttocampaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignaction',
            unique_together=set(),
        ),
    ]
