# Generated by Django 4.0.1 on 2022-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_alter_campaignaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttocampaign',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
