# Generated by Django 4.0.1 on 2022-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_contacttocampaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientphonenumber',
            name='phone_message_service_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
