# Generated by Django 4.0.1 on 2022-05-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0036_clientphonenumber_phone_message_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('field_name', models.CharField(blank=True, max_length=30, null=True)),
                ('field_type', models.CharField(blank=True, max_length=30, null=True)),
                ('client_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
