# Generated by Django 4.0.1 on 2022-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_customfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='active_campaign',
            field=models.ManyToManyField(blank=True, null=True, to='client.Campaign'),
        ),
    ]
