# Generated by Django 4.0.1 on 2022-05-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0038_contactuser_active_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsValue',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('field_value', models.TextField(blank=True, null=True)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contactuser')),
                ('custom_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.customfields')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
