# Generated by Django 4.0.1 on 2022-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_customfieldsvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='field_placeholder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
