# Generated by Django 4.0.1 on 2022-05-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_contacttocampaign_is_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='client_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
