# Generated by Django 4.0.1 on 2022-06-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0042_tags_client_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleOptinCampaign',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('campagin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.campaign')),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contactuser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
