# Generated by Django 4.0.1 on 2022-06-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
        ('client', '0043_doubleoptincampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneMessage',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('message', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
                ('is_receive', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.contactuser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
