# Generated by Django 4.0.1 on 2022-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0010_timezone_value'),
        ('client', '0046_contactuser_country_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReferralCampaigns',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('ref_camp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_read_count', models.IntegerField(blank=True, null=True)),
                ('max_read_count', models.IntegerField(blank=True, null=True)),
                ('client_rc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('ref_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_coupon', to='client.coupon')),
                ('reward_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_coupon', to='client.coupon')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
