# Generated by Django 4.0.1 on 2022-07-25 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0010_timezone_value'),
        ('client', '0047_coupon_is_referral_referralcampaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCampaignToContact',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_added', models.BooleanField(default=False)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to='client.contactuser')),
                ('refered_user', models.ManyToManyField(blank=True, null=True, related_name='refered_user', to='client.ContactUser')),
                ('referral_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.referralcampaigns')),
            ],
            options={
                'unique_together': {('referral_camp', 'contact_user')},
            },
            bases=('admin_user.activitytracking',),
        ),
    ]
