# Generated by Django 4.0.1 on 2022-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0048_referralcampaigntocontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusercoupon',
            name='second_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
