# Generated by Django 4.0.1 on 2022-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_coupon_is_referral_dis_coupon_is_referral_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusercoupon',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referralcampaigntocontact',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referralrewardcouponcontactuser',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
