# Generated by Django 4.0.1 on 2022-10-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0051_contactusercoupon_short_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Cleints'},
        ),
    ]
