# Generated by Django 4.0.1 on 2022-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_activitytracking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='time_zone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
