# Generated by Django 4.0.2 on 2022-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0005_timezone_alter_admin_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
