# Generated by Django 4.0.2 on 2022-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0006_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
