# Generated by Django 4.0.2 on 2022-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0007_alter_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_forget',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
