# Generated by Django 3.2.12 on 2022-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0008_admin_is_forget_alter_admin_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
