# Generated by Django 4.0.1 on 2022-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_alter_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
