# Generated by Django 4.0.1 on 2022-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0010_timezone_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('brand_image_full', models.ImageField(blank=True, null=True, upload_to='brand-images/')),
                ('brand_image_web', models.ImageField(blank=True, null=True, upload_to='brand-web-images/')),
                ('brand_image_mobile', models.ImageField(blank=True, null=True, upload_to='brand-mobile-images/')),
                ('brand_image_grayscale_full', models.ImageField(blank=True, null=True, upload_to='brand-grayscale-images/')),
                ('brand_image_grayscale_web', models.ImageField(blank=True, null=True, upload_to='brand-web-grayscale-images/')),
                ('brand_image_grayscale_mobile', models.ImageField(blank=True, null=True, upload_to='brand-mobile-grayscale-images/')),
                ('brand_image_darkmode_full', models.ImageField(blank=True, null=True, upload_to='brand-darkmode-images/')),
                ('brand_image_darkmode_web', models.ImageField(blank=True, null=True, upload_to='brand-web-darkmode-images/')),
                ('brand_image_darkmode_mobile', models.ImageField(blank=True, null=True, upload_to='brand-mobile-darkmode-images/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50)),
                ('featured_review', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review brand',
                'verbose_name_plural': 'Review brands',
                'db_table': 'review_brand',
            },
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['id'], name='review_bran_id_bfb5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['name'], name='review_bran_name_7cfe0b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['slug'], name='review_bran_slug_b0f334_idx'),
        ),
    ]
