# Generated by Django 4.0.1 on 2022-09-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0011_reviewbrand_reviewbrand_review_bran_id_bfb5e1_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewBrand',
        ),
    ]
