# Generated by Django 4.0.1 on 2022-02-06 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_user', '0002_activitytracking_address'),
        ('aegency_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AegencyUser',
            new_name='AgencyUser',
        ),
    ]
