# Generated by Django 4.0.1 on 2022-08-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0010_timezone_value'),
        ('aegency_user', '0004_agencyuser_support_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHostname',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_user.activitytracking')),
                ('host_id', models.CharField(blank=True, max_length=250, null=True)),
                ('hostname', models.CharField(blank=True, max_length=250, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aegency_user.agencyuser')),
            ],
            bases=('admin_user.activitytracking',),
        ),
    ]
