# Generated by Django 4.0.1 on 2022-09-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aegency_user', '0005_agencyhostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyhostname',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyhostname',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyuser',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aegency_user.agencyhostname'),
        ),
    ]
