# Generated by Django 4.0.1 on 2022-09-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aegency_user', '0006_agencyhostname_is_deleted_agencyhostname_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyhostname',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aegency_user.agencyuser'),
        ),
    ]
